//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDangKiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chuphuongtien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chuphuongtien()
        {
            this.lichdangkiems = new HashSet<lichdangkiem>();
            this.phuongtiens = new HashSet<phuongtien>();
        }
    
        public int maCPT { get; set; }
        public string cccd { get; set; }
        public string hoVaten { get; set; }
        public string soDT { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lichdangkiem> lichdangkiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phuongtien> phuongtiens { get; set; }
    }
}
