//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDangKiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dangkiemvien
    {
        public int maDKV { get; set; }
        public string hoVaten { get; set; }
        public string tenDangNhap { get; set; }
        public string matKhau { get; set; }
    }
}
