//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDangKiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lichdangkiem
    {
        public int maLDK { get; set; }
        public System.DateTime ngayDangkiem { get; set; }
        public System.DateTime ngayHethan { get; set; }
        public int maCPT { get; set; }
        public int maPT { get; set; }
        public int maTT { get; set; }
    
        public virtual chuphuongtien chuphuongtien { get; set; }
        public virtual phuongtien phuongtien { get; set; }
        public virtual trungtam trungtam { get; set; }
    }
}
