//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDangKiem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbdangkiemEntities : DbContext
    {
        public dbdangkiemEntities()
            : base("name=dbdangkiemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chuphuongtien> chuphuongtiens { get; set; }
        public virtual DbSet<dangkiemvien> dangkiemviens { get; set; }
        public virtual DbSet<lichdangkiem> lichdangkiems { get; set; }
        public virtual DbSet<phuongtien> phuongtiens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<trungtam> trungtams { get; set; }
    }
}
