//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDangKiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phuongtien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phuongtien()
        {
            this.lichdangkiems = new HashSet<lichdangkiem>();
        }
    
        public int maPT { get; set; }
        public string bienSoxe { get; set; }
        public string loaiXe { get; set; }
        public int loaiBien { get; set; }
        public int maCPT { get; set; }
    
        public virtual chuphuongtien chuphuongtien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lichdangkiem> lichdangkiems { get; set; }
    }
}
