//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDangKiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trungtam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trungtam()
        {
            this.lichdangkiems = new HashSet<lichdangkiem>();
        }
    
        public int maTT { get; set; }
        public string tenTrungtam { get; set; }
        public string diaChi { get; set; }
        public string khuVuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lichdangkiem> lichdangkiems { get; set; }
    }
}
